-- Operational schema (HEADERS ONLY). Generated by scripts/stage_dbs.py.
-- Bulk data is loaded from S3 by deployment/db-seed-job.yaml (too big for a CM).
-- Columns MUST match what services/mcp-* SELECT.
CREATE TABLE alerts (
    id text PRIMARY KEY, ts timestamptz NOT NULL, severity text,
    source_ip text, dest_ip text, rule_name text, description text);
CREATE TABLE assets (
    asset_id text PRIMARY KEY, hostname text, owner text, owner_contact text,
    criticality text, location text, os text, department text, last_seen timestamptz);
CREATE TABLE users (
    user_id text PRIMARY KEY, display_name text, department text, manager text,
    email text, privileged boolean, mfa_enrolled boolean);
CREATE TABLE iocs (
    indicator text PRIMARY KEY, verdict text, confidence double precision, source text);
CREATE TABLE runbook (
    id serial PRIMARY KEY, title text, steps jsonb, attack_ref text,
    source text, keywords text);
CREATE TABLE incidents (
    incident_id text PRIMARY KEY, status text, title text, description text,
    severity text, assignee text, created_at timestamptz, updated_at timestamptz, note text);
